In [2]:
import warnings
warnings.filterwarnings('ignore')

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['font.family'] ='Malgun Gothic'
#plt.rcParams['font.family'] = 'AppleGothic' # 맥
plt.rcParams['axes.unicode_minus'] =False

선형 회귀를 훈련시키는 방법

    - 닫힌 방정식 : 훈련 세트에 가장 잘 맞는 모델 파라미터 직접 계산
    
    - 경사 하강법(GD) : 반복적인 최적화 방식을 사용하여 모델 파라미터를 조금씩 바꾸면서 비용 함수를 훈련 세트에 대해 최소화

# 선형회귀

- 가중치 합과 편향이라는 상수를 더해 예측을 만든다

$ \widehat{y} = \theta_0 + \theta_1x_1 + \theta_2x_2 + ... + \theta_nx_n $( 편향 : $\theta_0$, 가중치 : $\theta_1, \theta_2 .., \theta_n$)

<br>
- 모델 훈련 : 모델이 훈련 세트에 가장 잘 맞도록 모델 파리미터를 설정 => RMSE

- RMSE를 최소화하는 $\theta$를 찾는다

In [4]:
np.random.seed(42)  # 동일하게 재현 가능하게 만들기 위해
m = 100  # 샘플 개수
X = 2 * np.random.rand(m, 1)  # 열 벡터
y = 4 + 3 * X + np.random.randn(m, 1)  # 열 벡터

X[:5]
y[:5]

array([[0.74908024],
       [1.90142861],
       [1.46398788],
       [1.19731697],
       [0.31203728]])

array([[6.33428778],
       [9.40527849],
       [8.48372443],
       [5.60438199],
       [4.71643995]])

In [5]:
# 사이킷런에서 선형회귀 수행

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X, y) # 학습

lr.intercept_ # 편향
lr.coef_ # 가중치

LinearRegression()

array([4.21509616])

array([[2.77011339]])

In [7]:
# 예측

X_new = np.array([[0], [2]])

lr.predict(X_new)

array([[4.21509616],
       [9.75532293]])

# 경사 하강법

- 여러 종류의 문제에서 최적의 해법을 찾을 수 있는 일반적인 최적화 알고리즘

- 비용 함수를 최소화하기 위해 반복해서 파라미터를 조정

- $\theta$를 임의의 값으로 시잓하여 한 번에 조금씩 비용 함수가 감소되는 방향으로 진행하여 알고리즘이 최솟값에 수렴할 때까지 점진적으로 향상

- 중요한 파라미터는 스탭의 크기로 학습률 하이퍼파라미터로 결정

- 경사 하강법 문제
    - 일찍 멈춰 전역 최솟값에 도달하짐 못 한다
    - 왼쪽에서 시작하면 전역 최솟값보다 덜 좋은 지역 최솟값에 도달한다

## 배치 경사 하강법

- 전체 학습 데이터를 하나의 배치로 묶어 학습시키는 경사 

- 전체 데이터에 대한 모델 오차의 평균을 구한 다음, 이를 이용해 미분을 통해 경사를 산출, 최적화를 진행

$\nabla_\eta MSE(\theta) = \begin{pmatrix} {\partial\over\partial\theta_0} MSE(\theta) \\ {\partial\over\partial\theta_1} MSE(\theta) \\ ... \\{\partial\over\partial\theta_n} MSE(\theta) \end{pmatrix} = {2\over m}X ^ T(X\theta - y) $

$\theta^{(next step)}= \theta - \eta\nabla_\theta MSE(\theta)$

In [10]:
from sklearn.preprocessing import add_dummy_feature


np.random.seed(42)  # 동일하게 재현 가능하게 만들기 위해
m = 100  # 샘플 개수
X = 2 * np.random.rand(m, 1)  # 열 벡터
y = 4 + 3 * X + np.random.randn(m, 1)  # 열 벡터
# y = 4 + 3X

X_b = add_dummy_feature(X) # 각 샘플에 x0 = 1을 추가

In [12]:
eta = 0.1 # 학습률(내려가는 스탭의 크기)
n_epochs = 1000 # 반복 
m = len(X_b) # 샘플 개수

np.random.seed(42)
theta = np.random.randn(2, 1) # 모델 파리미터를 랜덤으로 초기화

for epoch in range(n_epochs):
    gradients = 2 / m * X_b.T @ (X_b @ theta - y) #(@ : 행렬곱)
    theta = theta - eta * gradients

theta

array([[4.21509616],
       [2.77011339]])

반복 횟수를 아주 크게 지정하고 그레이디언트 벡터가 아주 작아지면 => 벡터의 노름이 어떤 값(허용오차)보다 작아지면 경사 하강법이 최솟값에 도달

## 확률적 경사 하강법

- 매 스텝에서 한 개의 샘플을 랜덤으로 선택하고 그 하나의 샘플에 대한 그레이디언트를 계산

- 매 반복에서 학습률을 결정하는 함수 : 학습 스케줄

In [ ]:
from sklearn.preprocessing import add_dummy_feature

np.random.seed(42)  # 동일하게 재현 가능하게 만들기 위해
m = 100  # 샘플 개수
X = 2 * np.random.rand(m, 1)  # 열 벡터
y = 4 + 3 * X + np.random.randn(m, 1)  # 열 벡터
# y = 4 + 3X

X_b = add_dummy_feature(X) # 각 샘플에 x0 = 1을 추가

In [13]:
# 간단한 학습 스케줄을 사용한 경사 하강법

n_epochs = 50
t0, t1 = 5, 50 # 학습 스케줄 파라미터

def learning_schedule(t):
    return t0 / (t + t1)

np.random.seed(42)
theta = np.random.randn(2, 1) # 랜덤 초기화

for epoch in range(n_epochs):
    for iteration in range(m):
        random_index = np.random.randint(m)
        xi = X_b[random_index:random_index + 1]
        yi = y[random_index:random_index + 1]
        gradients = 2 * xi.T @ (xi @ theta - yi) # SGD의 경우 m으로 나누지 않는다
        eta = learning_schedule(epoch * m + iteration)
        theta = theta - eta * gradients
        
theta

array([[4.21076011],
       [2.74856079]])