# 1.파이썬 자료형

## 1.숫자형

In [ ]:
import numpy as np

In [ ]:
a = 1234
b = -12.34
c = a + b

print(a, b)
print(type(a), type(b))
print(c)
print(type(c))


1234 -12.34
<class 'int'> <class 'float'>
1221.66
<class 'float'>


In [ ]:
a = 3
b = 7

print(a + b)
print(a - b)
print(a * b)
print(a / b) # 몫의 결과를 실수(float)
print(a ** b)
print(a % b) # 니머지
print(a // b) # 몫의 결과는 정수(int)

10
-4
21
0.42857142857142855
2187
3
0


## 2.문자열

In [ ]:
a = 'hello world'
b = "'hello python's world"
c = '"hello world". he says'
d = "helllo world\nlife is good"
e = "helllo world\tlife is good"


print(a)
print(b)
print(c)
print(d)
print(e)

hello world
'hello python's world
"hello world". he says
helllo world
life is good
helllo world	life is good


### 1.문자열 더하기

In [ ]:
# 문자열 더하기
a = 'python'
b = ' '
c = 'is good'

print(a + b+ c)

# 문자열 곱하기
a = 'python'

print(a * 3)


# 문자열 길이 구하기
a = 'life is short, python is valuable'
b = len(a)

print(b)


# 문자열 인덱싱
a = 'life is short, python is valuable'
b = a[0]
c = a[10]
d = a[-8]
e = a[-1]

print(b + c + d + e)


# 문자열 슬라이싱
a = 'life is short, python is valuable'
b = a[:4]
c = a[4:8]
d = a[25:]

print(b + c + d)


# 문자 개수 세기
a = 'apple'
b = a.count('a')

print(b)


# 문자 위치찾기
a = 'apple'
b = a.find('p')

print(b)


# 문자열 삽입
a = 'apple'
b = ','.join(a)

print(b)


# 소문자와 대문자 바꾸기
a = 'apple'
b = a.upper()
c = b.lower()

print(b)
print(c)


# 공백 지우기
a = ' apple '
b = a.lstrip()
c = a.rstrip()
d = a.strip()

print(b)
print(c)
print(d)


# 문자열 바꾸기
a = 'apple'
b = a.replace('a', 'e')

print(b)


# 문자열 나누기
a = 'apple, orange'
b = a.split() # 공백
c = a.split(',')

print(b)
print(c)

python is good
pythonpythonpython
33
love
life is valuable
1
1
a,p,p,l,e
APPLE
apple
apple 
 apple
apple
epple
['apple,', 'orange']
['apple', ' orange']


## 3.리스트

In [ ]:
# 리스트 요소의 수정과 삭제
a = [1, 2, 3, 4, 5]
a[2] = 10 # 수정
del a[4] # 삭제

print(a)


# 리스트 요소 추가
a = [1, 2, 3]
a.append(10) # 리스트 마지막에 추가

print(a)


# 리스트 정렬
a = [1, 5, 3, 7]
a.sort()

print(a)


# 리스트 요소의 위치 반환
a = [5, 4, 3, 2, 1]
b = a.index(3)
c = a.index(5)

print(b)
print(c)


# 리스트 요소 삽입
a = [1, 2, 3, 5]
a.insert(3, 4) # .insert(위치, 값)

print(a)


# 리스트 요소 제거
a = [4, 5, 6, 7, 2, 4]
a.remove(4)

print(a)


# 리스트 요소 뽑기
a = [4, 5, 6, 7, 2, 4]
b = a.pop(1) # pop(위치)

print(a)
print(b)


# 리스트 요소 개수 세기
a = [4, 5, 6, 7, 2, 4]
b = a.count(4)

print(b)

[1, 2, 10, 4]
[1, 2, 3, 10]
[1, 3, 5, 7]
2
0
[1, 2, 3, 4, 5]
[5, 6, 7, 2, 4]
[4, 6, 7, 2, 4]
5
2


## 4.딕셔너리

In [ ]:
a = {'name' : 'jonn', 'age' : 20, 'birth' : [11, 8]}

print(a)
print(a['name'])
print(a['birth'])

{'name': 'jonn', 'age': 20, 'birth': [11, 8]}
jonn
[11, 8]


In [ ]:
a = {'name' : 'jonn'}
a['age'] = 20
a['house'] = 'aprt'
a['birth'] = [11, 8]

print(a)

del a['birth']

print(a)

{'name': 'jonn', 'age': 20, 'house': 'aprt', 'birth': [11, 8]}
{'name': 'jonn', 'age': 20, 'house': 'aprt'}


In [ ]:
# 키 리스트
a = {'name' : 'jonn', 'age' : 20, 'birth' : [11, 8]}
b = a.keys()
c = list(a.keys())

print(b)
print(c)


# 값 리스트
a = {'name' : 'jonn', 'age' : 20, 'birth' : [11, 8]}
b = a.values()
c = list(a.values())

print(b)
print(c)


# 키 - 값 리스트
a = {'name' : 'jonn', 'age' : 20, 'birth' : [11, 8]}
b = a.items()
c = list(a.items())

print(b)
print(c)

# 키로 값 호출하기
a = {'name' : 'jonn', 'age' : 20, 'birth' : [11, 8]}
b = a.get('name')
c = a['name']
d = a.get('house')
e = a.get('house', 'No Date')

print(b)
print(c)
print(d)
print(e)

dict_keys(['name', 'age', 'birth'])
['name', 'age', 'birth']
dict_values(['jonn', 20, [11, 8]])
['jonn', 20, [11, 8]]
dict_items([('name', 'jonn'), ('age', 20), ('birth', [11, 8])])
[('name', 'jonn'), ('age', 20), ('birth', [11, 8])]
jonn
jonn
None
No Date


## 5.집합


- 집합은 순서가 없고 중복이 없다

In [ ]:
a = {1, 2, 3, 2, 1}
b = set([1, 2, 3, 2, 1])
c = set('python')

print(a)
print(b)
print(c)

{1, 2, 3}
{1, 2, 3}
{'t', 'y', 'h', 'n', 'p', 'o'}


In [ ]:
a = set([1, 2, 3])
b = list(a)
c = tuple(a)

print(a)
print(b)
print(b[0])
print(c)
print(c[2])

{1, 2, 3}
[1, 2, 3]
1
(1, 2, 3)
3


In [ ]:
# 교집합
a = set([1, 2, 3, 4, 5])
b = set([3, 4, 5, 6, 7])
c = a & b
d = a.intersection(b)

print(c)
print(d)


# 합집합
a = set([1, 2, 3, 4, 5])
b = set([3, 4, 5, 6, 7])
c = a | b
d = a.union(d)

print(c)
print(d)


# 차집합
a = set([1, 2, 3, 4, 5])
b = set([3, 4, 5, 6, 7])
c = a - b
d = a.difference(b)

print(c)
print(d)

{3, 4, 5}
{3, 4, 5}
{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5}
{1, 2}
{1, 2}


## 6.논리형

In [ ]:
a = True
b = False

print(a)
print(type(a))
print(b)
print(type(b))
print(a + b) #  True : 1, False : 0
print(type(a + b))
print(a * b)
print(type(a * b))

True
<class 'bool'>
False
<class 'bool'>
1
<class 'int'>
0
<class 'int'>


# 2.파이썬 제어문

## 1.if문

In [ ]:
a = True

if a :
    print('가설은')
    print('사실이다')
else:
    print('가설을')
    print('거짓이다')

가설은
사실이다


In [ ]:
x = 3
y = 7

if x <= 7:
    print('x가 y보다 작거나 같다')
else:
    print('x가 y보다 크다')

x가 y보다 작거나 같다


In [ ]:
x = 3
y = [1, 2, 3, 4, 5]

if x in y:
    print('데이터가 존재한다')
else:
    print('데이터가 존재하지 않는다')

데이터가 존재한다


In [ ]:
#elif문

x = 3
y = 7

if x == y:
    print('x와 y는 같다')
elif x < y:
    print('x가 y보다 작다')
else:
    print('x가 y보다 크다')

x가 y보다 작다


## 2.while문

In [ ]:
a = 0

while a < 5:
    print('a값은 %s입니다'%a)
    a += 1

print('while문이 종료되었습니다')

a값은 0입니다
a값은 1입니다
a값은 2입니다
a값은 3입니다
a값은 4입니다
while문이 종료되었습니다


In [ ]:
a = 0
b = ['사과', '바나나', '토마토']

while a < len(b):
    print('바구니에서 %s를 꺼냈습니다'%b[a])
    a += 1

print('바구니에 아무것도 남아있지 않습니다')

바구니에서 사과를 꺼냈습니다
바구니에서 바나나를 꺼냈습니다
바구니에서 토마토를 꺼냈습니다
바구니에 아무것도 남아있지 않습니다


In [ ]:
#break문

a = 5

while a > 0:
    print('a값은 %s입니다'%a)
    a -= 1

    if a == 2:
        break
print('while문 종료')

a값은 5입니다
a값은 4입니다
a값은 3입니다
while문 종료


In [ ]:
# continu문

a = 0
while a < 10:
    a += 1
    if a % 2 == 0:
        continue
    print(a)

1
3
5
7
9


## 3.for문

In [ ]:
a = ['사과', '바나나', '토마토']

for i in a:
    print(i)

사과
바나나
토마토


In [ ]:
a = [90, 25, 67, 45, 80]
b = sum(a) / len(a)

for i in a:
    if i > b:
        print('%d는 평균보다 크다'%i)
    else:
        print('%d는 평균보다 작거나 같다'%i)

90는 평균보다 크다
25는 평균보다 작거나 같다
67는 평균보다 크다
45는 평균보다 작거나 같다
80는 평균보다 크다


In [ ]:
for i in range(2, 10):
    for j in range(1, 10):
        print(i * j, end = ' ')
    print()

2 4 6 8 10 12 14 16 18 
3 6 9 12 15 18 21 24 27 
4 8 12 16 20 24 28 32 36 
5 10 15 20 25 30 35 40 45 
6 12 18 24 30 36 42 48 54 
7 14 21 28 35 42 49 56 63 
8 16 24 32 40 48 56 64 72 
9 18 27 36 45 54 63 72 81 


In [ ]:
a = [1, 2, 3, 4]
result = []

for i in a:
    result.insert(0, i * 10)

print(result)

a = [1, 2, 3, 4]
result = list(range(len(a)))
for i in range(1, len(a)+1):
     result[-i] = a[i - 1]*10

print(result)

[40, 30, 20, 10]
[40, 30, 20, 10]


# 3.파이썬 함수

In [ ]:
def add(a, b):
    return a + b

a = 3
b = 7
add(a, b)

10

# 4.numpy

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1, 2, 3])

print(a1)
print(type(a1))
print(a1.shape)

print()

a2 = np.array([[1, 2, 3], [4, 5, 6]])

print(a2)
print(type(a2))
print(a2.shape)

print()

a3 = np.array([[1, 2, 3]])

print(a3)
print(type(a3))
print(a3.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)

[[1 2 3]]
<class 'numpy.ndarray'>
(1, 3)


In [ ]:
# 차원 확인하기
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
2


In [ ]:
# 배열 만들기

a = np.arange(20)
print(a)

lst = list(range(0, 20))
print(lst)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
a = np.arange(1, 20, 3)
print(a)

[ 1  4  7 10 13 16 19]


## 1.numpy 배열 초기화

In [ ]:
zero_a = np.zeros((2, 5))
one_a = np.ones((3, 4))

print(zero_a)
print(one_a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# one_a를 0으로
zero_b = np.zeros_like(one_a)
print(zero_b)

# zero_a를 1로
one_b = np.ones_like(zero_a)
print(one_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 특정 상수인 배열 생성
full_a = np.full((4, 3), 9)
print(full_a)

# 임의의 값으로
random_a = np.random.random((3, 4))
print(random_a)


[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
[[0.17604245 0.9388533  0.03649341 0.18866148]
 [0.6444407  0.90040649 0.81291019 0.30377043]
 [0.16895649 0.77713664 0.35469933 0.40842205]]


In [ ]:
# 원소가 모두 1이고 나머지는 모두 0인 대각행렬
eye_a = np.eye(4)
print(eye_a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 2.numpy 배열 크기 변형

In [ ]:
a1 = np.arange(12)
print(a1)

a2 = a1.reshape(3, -1)
print(a2)

a3 = a1.reshape(3, -1, order = "F")
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
a1 = np.arange(12)
a2 = a1.reshape(2, 3, 2, order = 'F')

print(a2)
print(a2.ndim)
print(a2.shape)

print()

# 다차원을 1차원으로
a3 = a2.flatten()
print(a3)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
3
(2, 3, 2)

[ 0  6  2  8  4 10  1  7  3  9  5 11]


## 3.numpy 배열 데이터 추출하기

### 1.인덱싱

In [ ]:
a1 = np.arange(1, 10)
print(a1)

value1 = a1[2]
value2 = a1[-2]

print(value1)
print(value2)

[1 2 3 4 5 6 7 8 9]
3
8


In [ ]:
a1 = np.arange(1, 10)
a1 = a1.reshape(3, 3)
print(a1)

print(a1[0, 0])
print(a1[2, 2])
print(a1[2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
8


### 2.슬라이싱

In [ ]:
a1 = np.arange(1, 10)
print(a1)

print(a1[:3])
print(a1[3::])

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]


In [ ]:
a1 = np.arange(1, 10)
a1 = a1.reshape(3, 3)
print(a1)

print(a1[0:2, 0:2])

print()

print(a1[1:, :])

print()

print(a1[:2, 1:])

print()

print(a1[:2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]

[[4 5 6]
 [7 8 9]]

[[2 3]
 [5 6]]

[1 4]


### 3.numpy 선형대수 기본연산

In [ ]:
# 행렬 내적(행렬 곱)
a1 = np.arange(1, 7)
a1 = a1.reshape(2, 3)

a2 = np.arange(7, 13)
a2 = a2.reshape(3, 2)

dot_a = np.dot(a1, a2)
print(dot_a)

[[ 58  64]
 [139 154]]


In [ ]:
# 전치 행렬
a1 = np.arange(1, 7).reshape(2, 3)
print(a1)

trans_a = np.transpose(a1)
print(trans_a)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### 4.numpy 기술 통계

In [ ]:
# 배열 데이터 개수
a1 = np.array([3, 5, -5, 56, 3, 2, 78, 4, 5, -5, 3, 56, 90, 24, 46])
print(len(a1))

15


In [ ]:
# 평균, 분산, 표준편차 계산
print(np.mean(a1))
print(np.var(a1))
print(np.std(a1))

24.333333333333332
960.8888888888889
30.998207833500455


In [ ]:
# 최대, 최소, 중앙값 계산
print(np.max(a1))
print(np.min(a1))
print(np.median(a1))

90
-5
5.0


In [ ]:
# 사분위수 계산
print(np.percentile(a1, 25))
print(np.percentile(a1, 50))
print(np.percentile(a1, 75))

print()

print(np.quantile(a1, 0.25))
print(np.quantile(a1, 0.5))
print(np.quantile(a1, 0.75))


3.0
5.0
51.0

3.0
5.0
51.0


# 5.pandas

## 1.series와 dataframe 이해하기

In [ ]:
import pandas as pd

- series는 1차원 배열

In [ ]:
    s = pd.Series([1, 3, 5, 6, 8])
    print(s)
    print(s.index)
    print(s.values)

0    1
1    3
2    5
3    6
4    8
dtype: int64
RangeIndex(start=0, stop=5, step=1)
[1 3 5 6 8]


- dataframe은 2차원 행렬 구조의 테이블 형태

In [ ]:
v = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
c = ['c1', 'c2', 'c3']
i = ['i1', 'i2', 'i3']

df = pd.DataFrame(v, index = i, columns = c)
print(df)

    c1  c2  c3
i1   1   2   3
i2   4   5   6
i3   7   8   9


## 2.dataframe 생성

In [ ]:
d = [['100', '강백호', 9.7],
     ['101', '송태섭', 8.9],
     ['102', '서태웅', 9.3],
     ['103', '채치수', 6.1]]

df = pd.DataFrame(d, columns = ['번호', '이름', '점수'])
print(df)

    번호   이름   점수
0  100  강백호  9.7
1  101  송태섭  8.9
2  102  서태웅  9.3
3  103  채치수  6.1


In [ ]:
d = {'번호' : ['100', '101', '102', '103'],
    '이름' : ['강백호', '송태섭', '서태웅', '채치수'],
    '점수' : [9.7, 8.9, 9.3, 6.1]}

df = pd.DataFrame(d)
print(df)

    번호   이름   점수
0  100  강백호  9.7
1  101  송태섭  8.9
2  102  서태웅  9.3
3  103  채치수  6.1


In [ ]:
!git clone https://github.com/AnalyticsKnight/yemoonsaBigdata/

Cloning into 'yemoonsaBigdata'...
remote: Enumerating objects: 637, done.
remote: Counting objects: 100% (274/274), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 637 (delta 136), reused 184 (delta 109), pack-reused 363
Receiving objects: 100% (637/637), 10.76 MiB | 20.00 MiB/s, done.
Resolving deltas: 100% (321/321), done.


In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       popula

## 3.데이터프레임 흞어보기

In [ ]:
print(df.shape)
print(df.head(5))

(17000, 9)
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB
None


In [ ]:
# 컬럼의 기초 통계 정보
print(df.describe())

          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.00000

In [ ]:
print(df['housing_median_age'])

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ... 
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64


In [ ]:
print(df['housing_median_age'].value_counts()) # 분포도 확인

52.0    1052
36.0     715
35.0     692
16.0     635
17.0     576
34.0     567
33.0     513
26.0     503
18.0     478
25.0     461
32.0     458
37.0     437
15.0     416
19.0     412
28.0     400
27.0     397
24.0     389
31.0     384
30.0     384
20.0     383
23.0     382
29.0     374
21.0     373
14.0     347
22.0     323
38.0     318
42.0     308
39.0     302
44.0     296
43.0     286
13.0     249
40.0     249
45.0     235
41.0     232
10.0     226
11.0     208
5.0      199
46.0     196
12.0     192
8.0      178
47.0     175
9.0      172
4.0      161
7.0      151
48.0     135
6.0      129
50.0     112
49.0     111
2.0       49
3.0       46
51.0      32
1.0        2
Name: housing_median_age, dtype: int64


## 4.데이터프레임 컬럼 생성과 수정

In [ ]:
df['Age_0'] = 0
print(df.head(3))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   

   population  households  median_income  median_house_value  Age_0  
0      1015.0       472.0         1.4936             66900.0      0  
1      1129.0       463.0         1.8200             80100.0      0  
2       333.0       117.0         1.6509             85700.0      0  


In [ ]:
df['Age_by_10'] = df['housing_median_age'] // 10
print(df.head(3))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   

   population  households  median_income  median_house_value  Age_0  Age_by_10  
0      1015.0       472.0         1.4936             66900.0      0        1.0  
1      1129.0       463.0         1.8200             80100.0      0        1.0  
2       333.0       117.0         1.6509             85700.0      0        1.0  


In [ ]:
df['Age_by_10'] = df['Age_by_10'] * 10
print(df.head(3))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   

   population  households  median_income  median_house_value  Age_0  Age_by_10  
0      1015.0       472.0         1.4936             66900.0      0       10.0  
1      1129.0       463.0         1.8200             80100.0      0       10.0  
2       333.0       117.0         1.6509             85700.0      0       10.0  


In [ ]:
print(df['Age_by_10'].value_counts())

30.0    4770
20.0    3985
10.0    3739
40.0    2223
50.0    1196
0.0     1087
Name: Age_by_10, dtype: int64


## 5.데이터프레임 데이터 삭제

- axis = 1 : 컬럼을 기준

- axis = 0 : 행을 기준으로

- inplace = True : 원 데이터프레임의 데이터 삭제

In [ ]:
drop_df = df.drop('Age_0', axis = 1)
print(drop_df.head(3))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   

   population  households  median_income  median_house_value  Age_by_10  
0      1015.0       472.0         1.4936             66900.0       10.0  
1      1129.0       463.0         1.8200             80100.0       10.0  
2       333.0       117.0         1.6509             85700.0       10.0  


In [ ]:
drop_result = df.drop(['Age_0', 'Age_by_10'], axis = 1, inplace = True)
print(df.head(3))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  


In [ ]:
drop_df = df.drop([0, 1, 2], axis = 0)
print(drop_df.head(3))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   
5    -114.58     33.63                29.0       1387.0           236.0   

   population  households  median_income  median_house_value  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  
5       671.0       239.0         3.3438             74000.0  


## 6.데이터프레임 데이터 조회

In [ ]:
print(df['housing_median_age'].head(3))

print()

print(df[['housing_median_age', 'total_rooms']].head(3))

0    15.0
1    19.0
2    17.0
Name: housing_median_age, dtype: float64

   housing_median_age  total_rooms
0                15.0       5612.0
1                19.0       7650.0
2                17.0        720.0


In [ ]:
# 첫 3개 행 출력
print(df.iloc[:3])

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  


In [ ]:
# 조건을 이용하여
print(df[df['housing_median_age'] == 30].head(3))

     longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
26     -115.37     32.82                30.0       1602.0           322.0   
50     -115.52     34.22                30.0        540.0           136.0   
101    -115.59     32.69                30.0        935.0           177.0   

     population  households  median_income  median_house_value  
26       1130.0       335.0         3.5735             71100.0  
50        122.0        63.0         1.3333             42500.0  
101       649.0       148.0         2.5769             94400.0  


In [ ]:
print(df[(df['housing_median_age'] > 30) &
         (df['total_rooms'] < 100) &
         (df['median_income'] > 10)].head(3))


       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
6030     -118.22     34.06                52.0         48.0             6.0   
13055    -121.87     37.46                43.0         91.0            12.0   
14501    -122.14     37.50                46.0         30.0             4.0   

       population  households  median_income  median_house_value  
6030         41.0        10.0        10.2264            112500.0  
13055        58.0        16.0        15.0001            500001.0  
14501        13.0         5.0        15.0001            500001.0  


In [ ]:
con1 = df['housing_median_age'] > 30
con2 = df['total_rooms'] < 100
con3 = df['median_income'] > 10

print(df[con1 & con2 & con3].head(3))

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
6030     -118.22     34.06                52.0         48.0             6.0   
13055    -121.87     37.46                43.0         91.0            12.0   
14501    -122.14     37.50                46.0         30.0             4.0   

       population  households  median_income  median_house_value  
6030         41.0        10.0        10.2264            112500.0  
13055        58.0        16.0        15.0001            500001.0  
14501        13.0         5.0        15.0001            500001.0  


### 1.데이터프레임 iloc함수

In [ ]:
print(df.iloc[0, 2])

15.0


### 2.데이터프레임 loc함수

In [ ]:
print(df.loc[0, 'housing_median_age'])

15.0


In [ ]:
print(df.loc[0 : 4, 'housing_median_age'])

0    15.0
1    19.0
2    17.0
3    14.0
4    20.0
Name: housing_median_age, dtype: float64


In [ ]:
print(df.loc[df['housing_median_age'] == 30, ['housing_median_age', 'total_bedrooms']])

       housing_median_age  total_bedrooms
26                   30.0           322.0
50                   30.0           136.0
101                  30.0           177.0
343                  30.0           672.0
427                  30.0           289.0
...                   ...             ...
16786                30.0           930.0
16803                30.0           331.0
16926                30.0           393.0
16974                30.0           366.0
16985                30.0           634.0

[384 rows x 2 columns]


## 7.데이터프레임 데이터 정렬과 집계

In [ ]:
sort_df = df.sort_values('housing_median_age')
print(sort_df.head(3))

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
13708    -122.00     38.23                 1.0       2062.0           343.0   
10993    -120.93     37.65                 1.0       2254.0           328.0   
1353     -117.17     34.12                 2.0       3867.0           573.0   

       population  households  median_income  median_house_value  
13708       872.0       268.0         5.2636            191300.0  
10993       402.0       112.0         4.2500            189200.0  
1353       1275.0       433.0         5.4138            164400.0  


In [ ]:
sort_df = df.sort_values(by = ['housing_median_age', 'total_rooms'], ascending = False)
print(sort_df.head(3))

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
15772    -122.41     37.79                52.0       6016.0          2509.0   
15773    -122.41     37.79                52.0       5783.0          2747.0   
11163    -121.03     40.35                52.0       5486.0          1044.0   

       population  households  median_income  median_house_value  
15772      3436.0      2119.0         2.5166            275000.0  
15773      4518.0      2538.0         1.7240            225000.0  
11163      1977.0       754.0         2.1833             49500.0  


In [ ]:
print(df.sum() / df.count())

longitude               -119.562108
latitude                  35.625225
housing_median_age        28.589353
total_rooms             2643.664412
total_bedrooms           539.410824
population              1429.573941
households               501.221941
median_income              3.883578
median_house_value    207300.912353
dtype: float64


In [ ]:
print(df[['housing_median_age', 'total_rooms']].mean())

housing_median_age      28.589353
total_rooms           2643.664412
dtype: float64


In [ ]:
group_df = df.groupby('housing_median_age').mean()
print(group_df.head(3))

                     longitude   latitude  total_rooms  total_bedrooms  \
housing_median_age                                                       
1.0                -121.465000  37.940000  2158.000000      335.500000   
2.0                -119.035306  35.410816  5237.102041      871.448980   
3.0                -118.798478  35.164783  6920.326087     1190.826087   

                     population   households  median_income  \
housing_median_age                                            
1.0                  637.000000   190.000000       4.756800   
2.0                 2005.224490   707.122449       5.074237   
3.0                 2934.673913  1030.413043       5.572013   

                    median_house_value  
housing_median_age                      
1.0                      190250.000000  
2.0                      229438.836735  
3.0                      239450.043478  


In [ ]:
group_df = df.groupby('housing_median_age')[['total_rooms', 'total_bedrooms']].mean()
print(group_df.head(3))

                    total_rooms  total_bedrooms
housing_median_age                             
1.0                 2158.000000      335.500000
2.0                 5237.102041      871.448980
3.0                 6920.326087     1190.826087


In [ ]:
group_df = df.groupby('housing_median_age')['total_rooms'].agg(['min', 'max', 'sum'])
print(group_df.head(3))

                       min      max       sum
housing_median_age                           
1.0                 2062.0   2254.0    4316.0
2.0                   96.0  21897.0  256618.0
3.0                  475.0  21060.0  318335.0


## 8.데이터프레임 결측치 처리하기

In [ ]:
import numpy as np

In [ ]:
df['Age_na'] = np.nan
print(df.isnull())

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False   
1          False     False               False        False           False   
2          False     False               False        False           False   
3          False     False               False        False           False   
4          False     False               False        False           False   
...          ...       ...                 ...          ...             ...   
16995      False     False               False        False           False   
16996      False     False               False        False           False   
16997      False     False               False        False           False   
16998      False     False               False        False           False   
16999      False     False               False        False           False   

       population  households  median_income  media

In [ ]:
print(df.isnull().sum())

longitude                 0
latitude                  0
housing_median_age        0
total_rooms               0
total_bedrooms            0
population                0
households                0
median_income             0
median_house_value        0
Age_na                17000
dtype: int64


In [ ]:
df['Age_na'] = df['Age_na'].fillna(df['housing_median_age'].mean())
print(df.head(3))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   

   population  households  median_income  median_house_value     Age_na  
0      1015.0       472.0         1.4936             66900.0  28.589353  
1      1129.0       463.0         1.8200             80100.0  28.589353  
2       333.0       117.0         1.6509             85700.0  28.589353  


# 6.scikit - learn

Estimator : 학습(fit), 예측(predict)
  - 분류(classifier) : Decisiod Tree Classifier, Random Forest Classifier, Gradient Boosting Classifier, SVC, GaussianNB

  - 예측(Regressor) : Linear Regression, Ridge, Random Forest Regresser, Gradient Boosting Regression



## 1.scikit - learn 주요 모델


- 예제 테이터 : sklearn.datasets

- 변수 처리 : sklearn.preprocessing, sklearn.feature_selection, sklearn.feature_extraction

- 변수 처리 & 차원 축소 : sklearn.decomposition

- 데이터 분리, 검증 & 매개변수 튜닝 : sklearn.model_selection

- 평가 : sklearn.metrics

- 머신러닝 알고리즘 : sklearn.ensemble, sklearn.linear_model, sklearn.naive_bayes, sklearn,neighbors, sklearn.svm, sklearn.tree, sklearn.cluster

- 유틸리티 : sklearn.pipeline

## 2.scikit - learn 내장 데이터 세트

- datasets.load_boston

- datasets.load_breast_cancer

- datasets.load_diabetes

- datasets.load_digits

- datasets.load_iris

- datasets.make_classifications : 분류를 위한 데이터 세트를 생성

- datasets.make_blobs : 클러스터링을 위한 데이터 세트를 생성

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()
print(type(iris))

keys = iris.keys()
print(keys)

<class 'sklearn.utils._bunch.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


- feature_name : 독립 변수의 변수 명

- data : 독립 변수의 데이터 값

- target : 종속 변수의 데이터 값

- target_name : 종속 변수의 데이터 값의 의미

In [7]:
print(iris.feature_names)

print()

print(iris.target_names)

print()

print(iris['data'][:10])

print()

print(iris.target[:10])

print(iris.target[-10:-1])


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

['setosa' 'versicolor' 'virginica']

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

[0 0 0 0 0 0 0 0 0 0]
[2 2 2 2 2 2 2 2 2]


## 3.scikit - learn 머신러닝 만들어 보기

### 1.데이터 불러오기

In [9]:
import pandas as pd

df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['label'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

### 2.데이터 나누기

In [11]:
from sklearn.model_selection import train_test_split

data = iris.data
target = iris.target

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.2, random_state = 11)

print('train_dataset')
print('x_train : ', len(x_train))
print('y_train : ', len(y_train))

print()

print('test_dataset')
print('x_tset : ', len(x_test))
print('y_test : ', len(y_test))


train_dataset
x_train :  120
y_train :  120

test_dataset
x_tset :  30
y_test :  30


### 3.모델 학습

In [12]:
from sklearn.tree import DecisionTreeClassifier

df_clf = DecisionTreeClassifier(random_state = 11)
df_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=11)

### 4.모델 예측

In [13]:
from sklearn.metrics import accuracy_score

pred =df_clf.predict(x_test)

ac_score = accuracy_score(y_test, pred)

print("예측 정확도 : ", ac_score)

예측 정확도 :  0.9333333333333333


## 4.scikit - learn 데이터 전처리

### 1.레이블 인코딩

- Label Encoder를 생성 한 후 fit와 transform을 호출 후 레이블 인코딩을 수행

In [16]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', 'TV','냉장고', '컴퓨터', '컴퓨터']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print(labels)
print(encoder.classes_)

[0 1 2 3 0 1 3 3]
['TV' '냉장고' '전자레인지' '컴퓨터']


In [17]:
origns = encoder.inverse_transform(labels)

print(origns)

['TV' '냉장고' '전자레인지' '컴퓨터' 'TV' '냉장고' '컴퓨터' '컴퓨터']


### 2.원 - 핫 인코딩

In [22]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

labels = labels.reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print(oh_labels.toarray())

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


### 3.스케일링

- 표준화 : (x - 해당 데이터 세트의 평균) / 데이터 세트의 표준편자

- 정규화 : 최대 - 최소 정규화 (x - 최소) / (최대 - 최소)

In [23]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
data = iris.data
df = pd.DataFrame(data, columns = iris.feature_names)

print(df.mean())
print()
print(df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df)

iris_scaler = scaler.transform(df)
iris_scaler_df = pd.DataFrame(iris_scaler, columns = iris.feature_names)

print(iris_scaler_df.mean())
print(iris_scaler_df.var())


sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [30]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(df)

iris_scaler = scaler.transform(df)
iris_scaler_df = pd.DataFrame(iris_scaler, columns = iris.feature_names)

print(iris_scaler_df.min())
print(iris_scaler_df.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


- 학습 데이터로 fit이 적용된 스케일링 기준 정보를 그대로 테스트 데이터에 적용해야 한다

-> 테스트 데이터에 다시 fit을 적용해서는 안 된다

In [33]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0, 10).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaler = scaler.transform(train_array)

print(np.round(train_array.reshape(-1), 2))
print(np.round(train_scaler.reshape(-1), 2))

print()

# scaler.fit(test_array)
test_scaler = scaler.transform(test_array)

print(np.round(test_array.reshape(-1), 1))
print(np.round(test_scaler.reshape(-1), 1))

[0 1 2 3 4 5 6 7 8 9]
[0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]

[0 1 2 3 4 5]
[0.  0.1 0.2 0.3 0.4 0.6]
